### PR TITLE
Switch from JS custom variables to HTML meta tags

### PR DESCRIPTION
**Pull request by fofr**
Append page metadata as `govuk-` namespaced meta tags within the `<head>` tag, as an alternative to setting Google custom variables within a script tag. This removes Google specific implementation details (page level scope, custom variable name, custom variable slot), the `GOVUK.Analytics` namespace and an inline `<script>` tag.

Javascript within static will handle the setting of custom dimensions and variables for analytics, based on these meta tags. A WIP example of that can be found here: https://github.com/alphagov/static/commit/3c87c32cf379f34862b9a19c1c429f2cc5780f7c

## Example output

```html
<meta name="govuk:format" content="news">
<meta name="govuk:analytics:organisations" content="<D19><D20>">
<meta name="govuk:analytics:world-locations" content="<WL3>">
```

Prior discussion: https://github.com/alphagov/slimmer/pull/117

### CODE REVIEW

**Comment by benilovj** [comment]
:+1:

**Comment by bradleywright** [comment]
:+1: for the proposed HTML. Not reviewed the code though.

**Comment by dsingleton** [comment]
Only commenting on the `meta` tags, as i've not had time to read the bulk of the changes. 

The approach is :+1: but i'd recommend using different character for namespacing, so it's clear what is a many-word thing, vs a namespace. eg:

```
<meta name="govuk-analytics-world-locations" content="<WL3>">
```

Would be clearer as one of:

```
<meta name="govuk:analytics:world-locations" content="<WL3>">
<meta name="govuk.analytics.world-locations" content="<WL3>">
```

I don't have a strong preference on `.` vs `:`, Dublin Core uses `.`, which is pretty wide spread, but Open Graph uses `:`, which is probably ore recognisable. 

I know it's a little pedantic, but I think the readability is worth it :)

**Comment by dsingleton** [comment]
Read the rest, the rest generally looks good :+1:

It's nice to be rid of the `#ga-param` hack, but there are still a few [other](https://github.com/search?l=ruby&q=ga-params+%40alphagov&type=Code) [references](https://github.com/search?l=html%2Berb&q=ga-params+%40alphagov&type=Code):
- Slimmer test template can just be updated, I think
- Smart Answer compare task, this will need updating when, slimmer is upgraded on SA, to ignore the meta tags instead. Nothing needs doing now, other than giving smart answer folks a heads up (and maybe creating an issue to track it/add visibility?)

**Comment by fofr** [comment]
@dsingleton I agree about the namespacing, I've switched to using `:` in 430b7ff

**Comment by benilovj** [comment]
@bradleywright @edds do either of you have any objections to the chosen namespacing?

**Comment by dsingleton** [comment]
I'm happy with @fofr's name-spacing changes, but would like someone else to agree before merging.

**Comment by bradleywright** [comment]
All good here.

**Pull request merged**
