### PR TITLE
Version 11.1.0

### PR DESCRIPTION
**Pull request by fofr**
* Allow components in static to be loaded locally rather than over the network (#208)
* Replace deprecated `after_filter` in slimmer_template (#209)

### CODE REVIEW

**Comment by nickcolley** [comment]
Are you sure this should not be a 12. release? If we're expecting Rails 4 apps to break?

**Comment by tijmenb** [comment]
`after_action` is a Rails 4.0.2 thing as far as I can see: https://apidock.com/rails/v4.0.2/AbstractController/Callbacks/ClassMethods/after_action

**Comment by fofr** [comment]
@tijmenb @nickcolley I did what we did when we already removed `before_filter`:
https://github.com/alphagov/slimmer/blame/version-bump-local/CHANGELOG.md#L115

**Comment by fofr** [comment]
Version 12.0.0 with explicit changelog saying we're dropping Rails 4 support.

**Pull request merged**
